### ISSUE TITLE
Model::all() not scoped but Model::create() is... on the same model

### ISSUE THREAD

**Issue by joeserg** [AuraEQ/laravel-multi-tenant#26]
Hi, I'm having an odd issue with scoping queries... 

My User model contains:

```php
namespace Acme\User;

use LaravelBook\Ardent\Ardent;
use AuraIsHere\LaravelMultiTenant\Traits\TenantScopedModelTrait;

class User extends Ardent {

    use TenantScopedModelTrait;

    ...
```

I have a custom 'before' filter called `company`, which I use in my routes file:

```php
Route::group(array('prefix' => 'users', 'before' => 'company'), function()
{
    Route::get('/', 'UsersController@index');
    Route::get('create', 'UsersController@create');
    Route::post('create', 'UsersController@store');
    ...
});
```

Within the `company` filter, I get the current Company ID from the session and scope with:

```php
TenantScope::addTenant('company_id', Session::get('company_id') );
```

My `UsersController@store` method looks like:

```php
$user = new User();
$user->name = 'Joe';
$user->save();
```
...and as I would expect, creates a user called 'Joe' with the `company_id` value automagically set to `1`.

However, my `UsersController@index` method contains:

```php
$users = User::all();
```
...and it returns every user, instead of just users with a `company_id` of `1`.

Curiously, if I var_dump `TenantScope::getTenants()` on that same `index` method, I get:

```
array(1) { ["company_id"]=> string(1) "1" }
```

...which to me would imply that the tenant has been set correctly?

Any input would be greatly appreciated. This is an awesome package and I hope I've just overlooked something very stupid!

**Comment by rscafi** [comment]
I think that it is somehow related to `LaravelBook\Ardent\Ardent`.
This is how  the scope is made:

	public static function bootTenantScopedModelTrait()
	{
		$tenantScope = App::make("AuraIsHere\LaravelMultiTenant\TenantScope");

		// Add the global scope that will handle all operations except create()
		static::addGlobalScope($tenantScope);

		// Add an observer that will automatically add the tenant id when create()-ing
		static::creating(function (Model $model) use ($tenantScope)
		{
			$tenantScope->creating($model);
		});
	}

Perhaps `addGlobalScope` isn't working as supposed to because of Ardent.
Can you use the default model and give it a shot?

**Comment by HipsterJazzbo** [comment]
@joeserg Any luck with this? I agree that it's likely an issue with `Ardent`. please report  back with your findings. Thanks!
