### ISSUE TITLE
Tenancy on sub-domains

### ISSUE THREAD

**Issue by jbrooksuk** [AuraEQ/laravel-multi-tenant#29]
I've written a Laravel route filter that bases the tenancy on the sub-domain.

```php
public function filter(Route $route, Request $request)
{
    $subdomain = null;
    $host = $request->getHost();
    $parts = explode('.', $host);

    if (count($parts) > 2) {
        $subdomain = $parts[0];

        // Set the tenant scope.
        if ($tenant = $this->partner->findBySlug($subdomain, $host)) {
            TenantScopeFacade::addTenant('partner_id', $tenant->id);
        } else {
            // TODO: No tenant was found, so we need to return an error.
            TenantScopeFacade::addTenant('partner_id', 0);
        }
    }
}
```

The problem is that before this code can even be called on my routes, the package is telling me off:

```
AuraIsHere\LaravelMultiTenant\TenantScope: tenant column "partner_id" NOT found in tenants scope "[]"
```

Even if I modify the `TenantScope.php` file to disable it immediately, I get this error.

What can I do to avoid this?

**Comment by jbrooksuk** [comment]
CC @HipsterJazzbo.

**Comment by HipsterJazzbo** [comment]
It's difficult for me to diagnose this sort of thing without more code, but in general, no scoping should happen until the first time `addTenant()` is called. Is that what's happening?

**Comment by jbrooksuk** [comment]
It seems to be.

Before the filter is even called my app blows up with the code above.

**Comment by HipsterJazzbo** [comment]
I wonder if it could be something to do with missing `$tenantColumns` on a model? Do you have a situation where `$model->tenantColumns` is empty as well as `default_tenant_columns` in the config?

**Comment by jbrooksuk** [comment]
I set the config and have the column in the table ready. That's it?

**Comment by HipsterJazzbo** [comment]
My guess is that it'll be the global scope attempting to apply before any tenants are added.

This is sort of (not really) a feature, in that I thought it'd be better to have a failure in this case than silently not scope anything. 

You could avoid this issue (I think) by checking `count($this->getTenants())` in `apply()`, but it'd have the side effect of failing silently to scope in an instance where no tenants were added.

Not sure what the best fix is for that. Thoughts?

**Comment by HipsterJazzbo** [comment]
Further thought: Is it possible that this (apply being called when no tenants are set) could be the cause of #22 as well?

**Comment by jbrooksuk** [comment]
I'd say fail silently. The package shouldn't make itself the end of everything, but rather a helper to tenancy applications. At least, that's how I'd do it.

Regarding 22, it quite possibly could be the issue, at least in it makes sense.

**Comment by rscafi** [comment]
I'm using this package and also tenancy on subdomains with no problems now, but I remember running into this issue (or at least similar) at start. I will look at which I did to fix this.

**Comment by HipsterJazzbo** [comment]
@jbrooksuk (Back from lunch) Could you have a go, replacing `apply()` with this:

```php
public function apply(Builder $builder)
{
	if (! $this->enabled) return;

	$model = $builder->getModel();
	
	if (count($this->getTenants()) > 0)
	{
		// Use whereRaw instead of where to avoid issues with bindings when removing
		foreach ($this->getModelTenants($model) as $tenantColumn => $tenantId)
		{
			$builder->whereRaw($model->getTenantWhereClause($tenantColumn, $tenantId));
		}
	}
}
```

and see if it behaves correctly?

**Comment by HipsterJazzbo** [comment]
I'd appreciate if someone would test with this commit (`"aura-is-here/laravel-multi-tenant": "dev-master"`) and report back :)

**Comment by jbrooksuk** [comment]
I'll be able to test in a couple of hours. 6AM here :)

**Comment by HipsterJazzbo** [comment]
Ha, fair enough.

**Comment by jbrooksuk** [comment]
Giving this a go now :)

**Comment by jbrooksuk** [comment]
Darn it. I need the facade stuff changed too. I'll make a PR now.
