### ISSUE TITLE
undefined method Illuminate\Config\Repository::package() in Laravel 5

### ISSUE THREAD

**Issue by jojimail** [AuraEQ/laravel-multi-tenant#35]
In laravel 5 the Serviceprovider is throwing this error

    Call to undefined method Illuminate\Config\Repository::package() in   
    aura-is-here/laravel-multi-tenant/src/AuraIsHere/LaravelMultiTenant/LaravelMultiTenantServiceProvider.php on line 44

This is related to 
[https://laracasts.com/discuss/channels/general-discussion/l5-latest-commit-breaks-if-using-waygenerators-or-image-internvention?page=1](https://laracasts.com/discuss/channels/general-discussion/l5-latest-commit-breaks-if-using-waygenerators-or-image-internvention?page=1)

**Comment by HipsterJazzbo** [comment]
It's not really related to that. It's just that asset registration is different in L5.

I'll be hopefully getting to this this week. Thanks!

**Comment by hiddenl00p** [comment]
We are getting below error on upgrade to Laravel 5. 

Call to undefined method Illuminate\Config\Repository::package() in   
aura-is-here/laravel-multi-tenant/src/AuraIsHere/LaravelMultiTenant/LaravelMultiTenantServiceProvider.php on line 44
