### ISSUE TITLE
FindOrFail not in model anymore in L5

### ISSUE THREAD

**Issue by AlanRezende** [AuraEQ/laravel-multi-tenant#39]
Hi i was trying to use  the laravel-multi-tenant in Laravel 5 most of thing works fine, but the findOrFail in the trait that calls the parent::findOrFail does not work anymore because theres no FindOrFail in the eloquent model anymore, just in the builder. Anyone knows how can i have a workaround it?

```
/**
     * Override the default findOrFail method so that we can rethrow a more useful exception.
     * Otherwise it can be very confusing why queries don't work because of tenant scoping issues.
     *
     * @param       $id
     * @param array $columns
     *
     * @throws TenantModelNotFoundException
     */
    public static function findOrFail($id, $columns = ['*'])
    {
        try {
            return parent::findOrFail($id, $columns);
        } catch (ModelNotFoundException $e) {
            throw with(new TenantModelNotFoundException())->setModel(get_called_class());
        }
    }
```

**Comment by rscafi** [comment]
I guess that it's related to https://github.com/laravel/framework/pull/7048.

**Comment by rscafi** [comment]
It's related to https://github.com/laravel/framework/pull/7048.

I'm still testing, but I think that I fixed it by changing 
```
return parent::findOrFail($id, $columns);
```
with
```
return parent::query()->findOrFail($id, $columns);
```

**Comment by AlanRezende** [comment]
yes i tested your sugestion here and it works. Also if you use 
```
return call_user_func_array([static::query(), 'findOrFail'], [$id, $columns]);
```
It works too, i was using that workaround, but the 
```
return call_user_func_array([static::query(), 'findOrFail'], [$id, $columns]);
```
is much better.
