### ISSUE TITLE
Config publishing on package install is breaking.

### ISSUE THREAD

**Issue by etiennemarais** [AuraEQ/laravel-multi-tenant#41]
In the service provider, this line is failing on Laravel 5:

    // Register our config
    $this->app['config']->package('aura-is-here/laravel-multi-tenant', __DIR__.'/../../config');

I think `->package()` is replaced by `->publishes()`

    $configPath = __DIR__.'/../../config';
    $this->publishes([$configPath => config_path('config.php')]);

**Comment by AlanRezende** [comment]
There is already a PR with this issue: https://github.com/AuraEQ/laravel-multi-tenant/pull/33

I have changed what is sugested in this PR and it works fine

Also Make sure to make this change to make all fine with L5 https://github.com/AuraEQ/laravel-multi-tenant/pull/40

**Comment by HipsterJazzbo** [comment]
I'm merged #40. Finally.
