### ISSUE TITLE
Call to undefined method Illuminate\Config\Repository::package()

### ISSUE THREAD

**Issue by hiddenl00p** [AuraEQ/laravel-multi-tenant#43]
I see this was closed before but we are getting below error on upgrade to Laravel 5.

Call to undefined method Illuminate\Config\Repository::package() in

aura-is-here/laravel-multi-tenant/src/AuraIsHere/LaravelMultiTenant/LaravelMultiTenantServiceProvider.php on line 44

**Comment by wannymiarelli** [comment]
duplicate of #41.
Take a look here, it's all about L5 new package management.

**Comment by ndunn97** [comment]
Hi, 

I still seem to be getting this behavior, has this issue been closed yet?

Thanks

**Comment by HipsterJazzbo** [comment]
See #41
