### ISSUE TITLE
BadMethodCallException in ServiceProvider.php line 226

### ISSUE THREAD

**Issue by ndunn97** [AuraEQ/laravel-multi-tenant#44]
I followed the instructions on issue #41, commenting out the `$this->app['config']->package` part of the code and replacing it with the following:

        // Register our config
        //$this->app['config']->package('aura-is-here/laravel-multi-tenant', __DIR__.'/../../config');
        $configPath = __DIR__.'/../../config';
        $this->publishes([$configPath => config_path('config.php')]);

However, this makes Laravel throw the following error:

    BadMethodCallException in ServiceProvider.php line 226:
    Call to undefined method [package]

Any ideas?

**Comment by HipsterJazzbo** [comment]
That means you've still got a call to `package()` in there somewhere. However, I've literally just pushed an update, trying pulling `dev-master` and see if it works for you.

**Comment by ndunn97** [comment]
Excellent, no errors now! Thank you so much :smile:
