### ISSUE TITLE
Package Not L4 Compatible

### ISSUE THREAD

**Issue by djenniex** [AuraEQ/laravel-multi-tenant#48]
I tried installing dev-master today with the current version of the Laravel 4.2 framework, and the artisan configuration publish throws an error.

```
./artisan config:publish aura-is-here/laravel-multi-tenant
PHP Fatal error:  Call to undefined method AuraIsHere\LaravelMultiTenant\LaravelMultiTenantServiceProvider::mergeConfigFrom() in /code/app/vendor/aura-is-here/laravel-multi-tenant/src/AuraIsHere/LaravelMultiTenant/LaravelMultiTenantServiceProvider.php on line 37
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method AuraIsHere\\LaravelMultiTenant\\LaravelMultiTenantServiceProvider::mergeConfigFrom()","file":"\/code\/app\/vendor\/aura-is-here\/laravel-multi-tenant\/src\/AuraIsHere\/LaravelMultiTenant\/LaravelMultiTenantServiceProvider.php","line":37}}
```

This is because Laravel 4.2 SupportProvider does not have the [mergeConfigFrom function](https://github.com/illuminate/support/blob/4.2/ServiceProvider.php).

I believe this error was introduced in the PR [40](https://github.com/AuraEQ/laravel-multi-tenant/pull/40).

So either this package is L5 only, or there needs to be another fix to make it L4 compatible. Either way, the documentation for this package should be updated to reflect this.

**Comment by HipsterJazzbo** [comment]
dev-master won't work with L4. Try to latest tagged version, `1.0-RC2`
