### ISSUE TITLE
Separate branch for 4.2

### ISSUE THREAD

**Issue by jbrooksuk** [AuraEQ/laravel-multi-tenant#49]
Can you make a separate branch for 4.2 compatibility please? This is much easier than tags, plus you can accept PR's to it for the people who are writing projects and can't update to 5.

**Comment by ryanengland** [comment]
Yes please, this is really important. I've just run a composer update on a Laravel 4.2 install and it's screwed everything up, have had to roll back and lock composer down to commit ref 9140a72432d1ac8d1f3d4e09d0a390a98b2bc879 to ensure compatibility with 4.2. I can't see anywhere any mention of the upgrade to L5 and the readme still says L4.2

Cheers guys.

**Comment by jbrooksuk** [comment]
@HipsterJazzbo ping!

**Comment by LeonardoCaitano** [comment]
I agree!

**Comment by HipsterJazzbo** [comment]
Hey guys sorry, done.

**Comment by LeonardoCaitano** [comment]
how do I use the branch " laravel - 4.2" in my app? 

"aura-is-here/laravel-multi-tenant": "laravel-4.2"

not work.
