### ISSUE TITLE
Support: Tenant column, multiple TenantIds

### ISSUE THREAD

**Issue by diaspar** [AuraEQ/laravel-multi-tenant#50]
Let's say I only use one tenant column:

tenant

But I may want to get 2 different companies at once (without getting all companies)

tenant = A OR tenant = B

It seems you can add multiple tenant fields:

TenantScope::addTenant($tenantColumn, $tenantId)

 but not multiple values per one tenant field or am I wrong? If such a change should be made, maybe you can point out the place to extend your code.

**Comment by diaspar** [comment]
Well, I only needed this for one specific Entity. So manually I override this trait method inside the entity:

```
	public function getTenantWhereClause($tenantColumn, $tenantId)
	{
		return "({$this->getTable()}.{$tenantColumn} = '{$tenantId}') OR ({$this->getTable()}.{$tenantColumn} = 'edge_case') ";
	}
```
It works but it's not elegant or efficient ( I may need this on more entities)

**Comment by diaspar** [comment]
WOW

and OR statement is still 3 times slower than a IN statement. 

http://stackoverflow.com/questions/782915/mysql-or-vs-in-performance

so, I made this little change:

return "{$this->getTable()}.{$tenantColumn} IN ('{$tenantId}', '{$all}')";

I hope this helps someone else.

**Comment by HipsterJazzbo** [comment]
Thanks! I don't think I'll add this in general for now, but I'll chuck it on the list for later.
