### ISSUE TITLE
Route Model Bindings L5

### ISSUE THREAD

**Issue by Jmrich** [AuraEQ/laravel-multi-tenant#54]
Items are not scoped when using route model bindings.
In RouteServiceProvider I have this binding:
    $router->model('client','App\Client');
If I access a page: /client/{client} , and the Scope is NOT applied in the global middleware stack it will show data for other tenants. All queries are scoped correctly.

**Comment by HipsterJazzbo** [comment]
I'm sorry, I don't understand the issue. Could you try to restate?
