### ISSUE TITLE
Compatibility for L5.1

### ISSUE THREAD

**Issue by alleknalle** [AuraEQ/laravel-multi-tenant#56]
Can you bump up to L5.1?

**Comment by timbertens** [comment]
woud like to see that too... can you do this?

**Comment by alleknalle** [comment]
Hi Tim,

https://github.com/luizreginaldo/laravel-multi-tenant has already done that. You can use that fork :)

Met vriendelijke groet,

Jille Behm

Aanwezig: ma t/m vr 09:00 - 17:30

Etocom
Energiestraat 28
1411 AT Naarden
www.etocom.nl<http://www.etocom.nl/>

[logo]

[T] 035-6720849
[F] 035-6720850


Like ons op Facebook: Etocom op Facebook<http://www.facebook.com/pages/EtoCom-Productions/199091133453617>

Van: Tim Bertens [mailto:notifications@github.com]
Verzonden: vrijdag 3 juli 2015 16:47
Aan: AuraEQ/laravel-multi-tenant
CC: Jille Behm
Onderwerp: Re: [laravel-multi-tenant] Compatibility for L5.1 (#56)


woud like to see that too... can you do this?

**Comment by timkley** [comment]
+1

**Comment by jorisnoo** [comment]
👍

**Comment by rafael-iop** [comment]
+1

**Comment by timbertens** [comment]
Can you process the pull request please?

**Comment by ryross** [comment]
I would also appreciate this. Thank you :)

**Comment by divdax** [comment]
Yeah, please update! :)

**Comment by adamthebig** [comment]
+1

**Comment by HipsterJazzbo** [comment]
Done
