### ISSUE TITLE
usage understanding

### ISSUE THREAD

**Issue by illuminate3** [AuraEQ/laravel-multi-tenant#57]
I was wondering how do you go about associating the tenant to say a sub.domain?

Thanks!

**Comment by illuminate3** [comment]
glitter comments have taken care of my question

**Comment by patroniton** [comment]
Could you shed some light on what you found @illuminate3? I'm currently working on multi-tenancy in an application and I would like to use a sub.domain approach and I'm not too sure on where to start. Any help would be appreciated.
