### ISSUE TITLE
LaravelMultiTenantServiceProvider updates break Laravel 4.x support

### ISSUE THREAD

**Issue by streicher** [AuraEQ/laravel-multi-tenant#59]
I'm running Laravel 4.2 and can't get the package to run because the latest two commits to LaravelMultiTenantServiceProvider by @AlanRezende  (9508388cce771d2ae7ed19c96c76cab5fa99c5fe,  c0f8c3bfaea45eb14d74553e35c08b733e014a48) break support for 4.x.

Here's the first exception I get:
```    
Call to undefined method
AuraIsHere\LaravelMultiTenant\LaravelMultiTenantServiceProvider::mergeConfigFrom()
```
at line 30...
```
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        // Merge the package config values so they don't have to have a complete configuration
        $this->mergeConfigFrom(__DIR__ . '/../../config/config.php', 'tenant');
 
        // Register our tenant scope instance
```
Do you all still intend to target 4.2 per the package description going forward or is this intentional?

**Comment by timkley** [comment]
Had the same problem, you have to use RC2.
streicher <notifications@github.com> schrieb am Mi., 15. Juli 2015 um 17:38:
