### ISSUE TITLE
Not scoping on Eloquent orWhere() method

### ISSUE THREAD

**Issue by patroniton** [AuraEQ/laravel-multi-tenant#62]
When performing a query on a model like so:

`Employee::where('first_name', 'John')->orWhere('last_name', 'Doe')->get();`

The first `where` is scoped correctly, however the `orWhere` will return any match regardless of the Employee's tenant_id.

Example: I have one employee named John for tenant 1, and I have three employees with the last name Doe for tenant 2. If I run the above query, it will return all four employees.

Not sure if this is a limitation via the `orWhere` method bypassing the tenant id check or a bug or whatever. I didn't see anything about this in the discussions here so I thought I'd bring it up.

**Update**:

Using the `Employee::where(function($query)` syntax and then putting the `where` conditions inside the function work. Example:

	Employee::where(function($query) {
		$query->where('first_name', 'John');
		$query->orWhere('last_name', 'Doe');
	})->get();

The above query works as expected. Is this just how we're supposed to do `orWhere` logic with these queries? Apologies if this is a stupid question/issue.

**Comment by HipsterJazzbo** [comment]
Well. Shit.

**Comment by HipsterJazzbo** [comment]
I think your workaround might be the only way. I'll put some thought into it but I can't think of anything better right now.

**Comment by Feijs** [comment]
I encountered this issue yesterday as well. I might have found a workable solution though:

The model query now maintains a nested subquery in which it pushes all (or)Where queries. This way orWhere conditions do not override the global client scope.

I've only had time to test it on simple queries though. Will need to check whether we also need to override other functions such as whereHas etc. 

(https://github.com/Feijs/laravel-multi-tenant/commit/031a18bbaad9b608519f1acb1efa3d91e313b9e8)

**Comment by HipsterJazzbo** [comment]
Hi! I've updated and moved this package to https://github.com/HipsterJazzbo/Landlord. Im still not sure that this is the best solution to this problem, but maybe we can re-open and discuss it over there?
