### ISSUE TITLE
Why is addTenant(tenantColumn, tenantId) - why is tenantColumn mandatory?

### ISSUE THREAD

**Issue by dschallert** [AuraEQ/laravel-multi-tenant#63]
I'm doing that one most of the time:

$this->tenantScope->addTenant(config('tenant.default_tenant_columns')[0], $this->instance_id);

Just wondered, why addTenant() needs the tenantColumn parameter again.

Thanks & Cheers

**Comment by HipsterJazzbo** [comment]
Ah yes. It's for flexibility. At first you could only use the column defined in the config, but now the library will allow any number of columns, so you could put whatever you wanted in there.

Might have a look at a better way to do this at some point, but there are some pretty basic issues with global scopes that I'm sort of waiting to see if Taylor has a solution for :)
