### ISSUE TITLE
Non-static method AuraIsHere\LaravelMultiTenant\TenantScope::addTenant() should not be called statically, assuming $this from incompatible context

### ISSUE THREAD

**Issue by Wipsly** [AuraEQ/laravel-multi-tenant#64]
Hi, 

I use this package with laravel 5.1 but I have one problem. I added the Default authenticate of Laravel:

    public function handle($request, Closure $next)
        {
            if ($this->auth->guest()) {
                if ($request->ajax()) {
                    return response('Unauthorized.', 401);
                } else {
                    return redirect()->guest('auth/login');
               }
           }

            // Get logged in user company id  
                $company = $this->auth->user()->company_id;  
  
           // Set tenant (client_id) based contex  
                TenantScope::addTenant('company_id', $company);  

            return $next($request);
         }
When I Login I get the following error:

Non-static method AuraIsHere\LaravelMultiTenant\TenantScope::addTenant() should not be called statically, assuming $this from incompatible context

Can anyone help me?

Thanks.

//UPDATE:

I created a new Middleware but I get the same error. My Middleware

    <?php

     namespace App\Http\Middleware;

    use Closure;

    use Auth;
    use AuraIsHere\LaravelMultiTenant\TenantScope;

    class TenantMiddleware
    {
        /**
         * Handle an incoming request.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  \Closure  $next
         * @return mixed
         */
        public function handle($request, Closure $next)
        {

            $company = Auth::user()->company_id;
            TenantScope::addTenant('company_id', $company);

            return $next($request);
        }
    }

**Comment by Wipsly** [comment]
I found the error... So stupid... One missing backslash...

    \TenantScope::addTenant('company_id', $company);

**Comment by HipsterJazzbo** [comment]
Ah yes, using Facades within a namespace. Glad you figured it out.

**Comment by MartinTale** [comment]
This should be in the readme.. Like me who's new to laravel these small things are quite important :)

**Comment by lagbox** [comment]
What should be in the readme ?

**Comment by MartinTale** [comment]
Backslash before TenantScope.. It's probably general knowledge for most but I got confused at the beginning..

**Comment by lagbox** [comment]
Ah, that is just a PHP thing (namespacing).

I see exactly what you are saying, but it is kinda difficult to write general documentation for something that uses Laravel (which uses PHP) if there isn't an assumption of a general knowledge of the underlying language ahead of time, let alone Laravel, because where do you draw the line otherwise :).

To anyone who may be having any trouble with namespacing btw, I feel this article is a great introduction.

 [Matt Stauffer - A Brief Introduction to PHP Namespacing](http://mattstauffer.co/blog/a-brief-introduction-to-php-namespacing).
