### ISSUE TITLE
Only one tenant allowed per request

### ISSUE THREAD

**Issue by cmigue** [AuraEQ/laravel-multi-tenant#65]
I'm developing a multi-tenant application and my design allows for multiple tenants per user.

For this I have a many-to-many relation between the users table and the sites table (sites is where the different tenants are configured).

I created a middleware to set the tenant on each request, which basically does this:

$tenantColumn = 'site_id';
$sites = Auth::user()->sites()->get();
foreach($sites as $site)   {
    TenantScope::addTenant($tenantColumn, $site->id);
}

I then associated 2 site IDs to the same user, but after testing, I only got the records related to the last site id associated to the user. 

I later found this while digging in TenantScope.php (line 42)

$this->tenants[$tenantColumn] = $tenantId;

I didn't have to dig further, since this made clear that only one tenant scope is allowed at the same time, the tenant id value is overwritten after each addTenant call.

Are there any plans to support multiple scopes simultaneously?

Regards.

**Comment by HipsterJazzbo** [comment]
No sorry. That's outside the scope of this package unfortunately.
