### ISSUE TITLE
Scope when no user authenticated

### ISSUE THREAD

**Issue by Jmrich** [AuraEQ/laravel-multi-tenant#70]
What is the recommended way to scope the queries when no user is authenticated? Currently it gets the tenant column from the authenticated user, but I need to be able to scope the queries for some commands that run when a user isn't logged in. Possibly in the constructor of the current class?

**Comment by HipsterJazzbo** [comment]
Hi! I've updated and moved this package to https://github.com/HipsterJazzbo/Landlord. Feel free to reopen this issue there if you like.

**Comment by ghost** [comment]
@Jmrich how you are doing with this ?
