### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by jbrooksuk** [AuraEQ/laravel-multi-tenant#71]
Add compatibility for Laravel 5.2

**Comment by igortrinidad** [comment]
Hi,
Sorry, but i can't install the package with this change ("illuminate/support": "4.2.*|5.0.*|5.1.*|5.2.*")...
It's getting this error on composer: 
Problem 1
    - Conclusion: remove laravel/framework v5.2.5...
- Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Installation request for aura-is-here/laravel-multi-tenant dev-master -> satisfiable by aura-is-here/laravel-multi-tenant[dev-master].
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - aura-is-here/laravel-multi-tenant dev-master requires illuminate/support 4.2.*|5.0.*|5.1.* -> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8].

Someone knows how to fix it?

**Comment by nathanjdunn** [comment]
I'm having the same issue. 

@HipsterJazzbo, could you merge @jbrooksuk's pull request so Laravel 5.2 is supported please?

**Comment by igortrinidad** [comment]
Hi @nathanjdunn , fork the package and update the composer.json like this:


{
    "name": "aura-is-here/laravel-multi-tenant",
    "description": "",
    "authors": [
        {
            "name": "Caleb Fidecaro",
            "email": "caleb@auraeq.com"
        }
    ],
    "require": {
        "php": ">=5.4.0",
        "illuminate/support": "4.2.*|5.0.*|5.1.*|5.2.*"
    },
    "require-dev": {
        "mockery/mockery": "~0.9",
        "phpunit/phpunit": "~4.0",
        "laravel/framework": "4.2.*|5.0.*|5.1.*|5.2.*"
    },
    "autoload": {
        "psr-4": {
            "AuraIsHere\\LaravelMultiTenant\\": "src/AuraIsHere/LaravelMultiTenant/"
        }
    }
}

**Comment by jbrooksuk** [comment]
You could also add a `repositories` item to use the fork version instead.

**Comment by illuminate3** [comment]
How do you use the repositories to use the fork?

**Comment by jbrooksuk** [comment]
Add this:

```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/JamesForks/laravel-multi-tenant"
        }
]
```

**Comment by illuminate3** [comment]
Awesome! Thanks!

Have you thought of just forking and running your own repo for this?

**Comment by jbrooksuk** [comment]
> Have you thought of just forking and running your own repo for this?

I'm likely going to write my own package to be honest. We use multi tenancy in a work project, so it's imperative that it works.
