### ISSUE TITLE
Landlord doesn't scope update or delete queries. 

### ISSUE THREAD

**Issue by techdaddies-kevin** [AuraEQ/laravel-multi-tenant#81]
Is this on purpose? It appears that it only scopes create queries and selects, but not updates or deletes. I'm thinking that this is happening because the select query that is run right before the update/delete IS scoped, but I just want to make sure that this is proper behavior before continuing down this path.

**Comment by hipsterjazzbo** [comment]
I'm not totally convinced one way or the other, but this is the wrong repo for Landlord anyway. Have a look here, chime in if you've got some thoughts: HipsterJazzbo/Landlord#15

**Comment by techdaddies-kevin** [comment]
My bad. Wasn't even paying attention where I was posting. Will contribute in that issue.
